--- !ditz.rubyforge.org,2008-03-06/project 
name: phparmory
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: phparmory
- !ditz.rubyforge.org,2008-03-06/component 
  name: phpArmory class
- !ditz.rubyforge.org,2008-03-06/component 
  name: phpArmoryCache class
- !ditz.rubyforge.org,2008-03-06/component 
  name: Examples
- !ditz.rubyforge.org,2008-03-06/component 
  name: Documentation
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: phpArmory 0.4.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-09-29 10:33:34.074704 Z
    - Daniel S. Reichenbach <shiendra@marenkay.com>
    - created
    - |-
      phpArmory 0.4.0 should include the class conversion to PHP5 classes,
      and complete API documentation for phpArmory and phpArmoryCache.
